package shared

import (
	"time"
)

type TeamTimezoneEnum string

const (
	TeamTimezoneEnumAfricaAbidjan               TeamTimezoneEnum = "Africa/Abidjan"
	TeamTimezoneEnumAfricaAccra                 TeamTimezoneEnum = "Africa/Accra"
	TeamTimezoneEnumAfricaAddisAbaba            TeamTimezoneEnum = "Africa/Addis_Ababa"
	TeamTimezoneEnumAfricaAlgiers               TeamTimezoneEnum = "Africa/Algiers"
	TeamTimezoneEnumAfricaAsmara                TeamTimezoneEnum = "Africa/Asmara"
	TeamTimezoneEnumAfricaBamako                TeamTimezoneEnum = "Africa/Bamako"
	TeamTimezoneEnumAfricaBangui                TeamTimezoneEnum = "Africa/Bangui"
	TeamTimezoneEnumAfricaBanjul                TeamTimezoneEnum = "Africa/Banjul"
	TeamTimezoneEnumAfricaBissau                TeamTimezoneEnum = "Africa/Bissau"
	TeamTimezoneEnumAfricaBlantyre              TeamTimezoneEnum = "Africa/Blantyre"
	TeamTimezoneEnumAfricaBrazzaville           TeamTimezoneEnum = "Africa/Brazzaville"
	TeamTimezoneEnumAfricaBujumbura             TeamTimezoneEnum = "Africa/Bujumbura"
	TeamTimezoneEnumAfricaCairo                 TeamTimezoneEnum = "Africa/Cairo"
	TeamTimezoneEnumAfricaCasablanca            TeamTimezoneEnum = "Africa/Casablanca"
	TeamTimezoneEnumAfricaCeuta                 TeamTimezoneEnum = "Africa/Ceuta"
	TeamTimezoneEnumAfricaConakry               TeamTimezoneEnum = "Africa/Conakry"
	TeamTimezoneEnumAfricaDakar                 TeamTimezoneEnum = "Africa/Dakar"
	TeamTimezoneEnumAfricaDarEsSalaam           TeamTimezoneEnum = "Africa/Dar_es_Salaam"
	TeamTimezoneEnumAfricaDjibouti              TeamTimezoneEnum = "Africa/Djibouti"
	TeamTimezoneEnumAfricaDouala                TeamTimezoneEnum = "Africa/Douala"
	TeamTimezoneEnumAfricaElAaiun               TeamTimezoneEnum = "Africa/El_Aaiun"
	TeamTimezoneEnumAfricaFreetown              TeamTimezoneEnum = "Africa/Freetown"
	TeamTimezoneEnumAfricaGaborone              TeamTimezoneEnum = "Africa/Gaborone"
	TeamTimezoneEnumAfricaHarare                TeamTimezoneEnum = "Africa/Harare"
	TeamTimezoneEnumAfricaJohannesburg          TeamTimezoneEnum = "Africa/Johannesburg"
	TeamTimezoneEnumAfricaJuba                  TeamTimezoneEnum = "Africa/Juba"
	TeamTimezoneEnumAfricaKampala               TeamTimezoneEnum = "Africa/Kampala"
	TeamTimezoneEnumAfricaKhartoum              TeamTimezoneEnum = "Africa/Khartoum"
	TeamTimezoneEnumAfricaKigali                TeamTimezoneEnum = "Africa/Kigali"
	TeamTimezoneEnumAfricaKinshasa              TeamTimezoneEnum = "Africa/Kinshasa"
	TeamTimezoneEnumAfricaLagos                 TeamTimezoneEnum = "Africa/Lagos"
	TeamTimezoneEnumAfricaLibreville            TeamTimezoneEnum = "Africa/Libreville"
	TeamTimezoneEnumAfricaLome                  TeamTimezoneEnum = "Africa/Lome"
	TeamTimezoneEnumAfricaLuanda                TeamTimezoneEnum = "Africa/Luanda"
	TeamTimezoneEnumAfricaLubumbashi            TeamTimezoneEnum = "Africa/Lubumbashi"
	TeamTimezoneEnumAfricaLusaka                TeamTimezoneEnum = "Africa/Lusaka"
	TeamTimezoneEnumAfricaMalabo                TeamTimezoneEnum = "Africa/Malabo"
	TeamTimezoneEnumAfricaMaputo                TeamTimezoneEnum = "Africa/Maputo"
	TeamTimezoneEnumAfricaMaseru                TeamTimezoneEnum = "Africa/Maseru"
	TeamTimezoneEnumAfricaMbabane               TeamTimezoneEnum = "Africa/Mbabane"
	TeamTimezoneEnumAfricaMogadishu             TeamTimezoneEnum = "Africa/Mogadishu"
	TeamTimezoneEnumAfricaMonrovia              TeamTimezoneEnum = "Africa/Monrovia"
	TeamTimezoneEnumAfricaNairobi               TeamTimezoneEnum = "Africa/Nairobi"
	TeamTimezoneEnumAfricaNdjamena              TeamTimezoneEnum = "Africa/Ndjamena"
	TeamTimezoneEnumAfricaNiamey                TeamTimezoneEnum = "Africa/Niamey"
	TeamTimezoneEnumAfricaNouakchott            TeamTimezoneEnum = "Africa/Nouakchott"
	TeamTimezoneEnumAfricaOuagadougou           TeamTimezoneEnum = "Africa/Ouagadougou"
	TeamTimezoneEnumAfricaPortoNovo             TeamTimezoneEnum = "Africa/Porto-Novo"
	TeamTimezoneEnumAfricaSaoTome               TeamTimezoneEnum = "Africa/Sao_Tome"
	TeamTimezoneEnumAfricaTripoli               TeamTimezoneEnum = "Africa/Tripoli"
	TeamTimezoneEnumAfricaTunis                 TeamTimezoneEnum = "Africa/Tunis"
	TeamTimezoneEnumAfricaWindhoek              TeamTimezoneEnum = "Africa/Windhoek"
	TeamTimezoneEnumAmericaAdak                 TeamTimezoneEnum = "America/Adak"
	TeamTimezoneEnumAmericaAnchorage            TeamTimezoneEnum = "America/Anchorage"
	TeamTimezoneEnumAmericaAnguilla             TeamTimezoneEnum = "America/Anguilla"
	TeamTimezoneEnumAmericaAntigua              TeamTimezoneEnum = "America/Antigua"
	TeamTimezoneEnumAmericaAraguaina            TeamTimezoneEnum = "America/Araguaina"
	TeamTimezoneEnumAmericaArgentinaBuenosAires TeamTimezoneEnum = "America/Argentina/Buenos_Aires"
	TeamTimezoneEnumAmericaArgentinaCatamarca   TeamTimezoneEnum = "America/Argentina/Catamarca"
	TeamTimezoneEnumAmericaArgentinaCordoba     TeamTimezoneEnum = "America/Argentina/Cordoba"
	TeamTimezoneEnumAmericaArgentinaJujuy       TeamTimezoneEnum = "America/Argentina/Jujuy"
	TeamTimezoneEnumAmericaArgentinaLaRioja     TeamTimezoneEnum = "America/Argentina/La_Rioja"
	TeamTimezoneEnumAmericaArgentinaMendoza     TeamTimezoneEnum = "America/Argentina/Mendoza"
	TeamTimezoneEnumAmericaArgentinaRioGallegos TeamTimezoneEnum = "America/Argentina/Rio_Gallegos"
	TeamTimezoneEnumAmericaArgentinaSalta       TeamTimezoneEnum = "America/Argentina/Salta"
	TeamTimezoneEnumAmericaArgentinaSanJuan     TeamTimezoneEnum = "America/Argentina/San_Juan"
	TeamTimezoneEnumAmericaArgentinaSanLuis     TeamTimezoneEnum = "America/Argentina/San_Luis"
	TeamTimezoneEnumAmericaArgentinaTucuman     TeamTimezoneEnum = "America/Argentina/Tucuman"
	TeamTimezoneEnumAmericaArgentinaUshuaia     TeamTimezoneEnum = "America/Argentina/Ushuaia"
	TeamTimezoneEnumAmericaAruba                TeamTimezoneEnum = "America/Aruba"
	TeamTimezoneEnumAmericaAsuncion             TeamTimezoneEnum = "America/Asuncion"
	TeamTimezoneEnumAmericaAtikokan             TeamTimezoneEnum = "America/Atikokan"
	TeamTimezoneEnumAmericaBahia                TeamTimezoneEnum = "America/Bahia"
	TeamTimezoneEnumAmericaBahiaBanderas        TeamTimezoneEnum = "America/Bahia_Banderas"
	TeamTimezoneEnumAmericaBarbados             TeamTimezoneEnum = "America/Barbados"
	TeamTimezoneEnumAmericaBelem                TeamTimezoneEnum = "America/Belem"
	TeamTimezoneEnumAmericaBelize               TeamTimezoneEnum = "America/Belize"
	TeamTimezoneEnumAmericaBlancSablon          TeamTimezoneEnum = "America/Blanc-Sablon"
	TeamTimezoneEnumAmericaBoaVista             TeamTimezoneEnum = "America/Boa_Vista"
	TeamTimezoneEnumAmericaBogota               TeamTimezoneEnum = "America/Bogota"
	TeamTimezoneEnumAmericaBoise                TeamTimezoneEnum = "America/Boise"
	TeamTimezoneEnumAmericaCambridgeBay         TeamTimezoneEnum = "America/Cambridge_Bay"
	TeamTimezoneEnumAmericaCampoGrande          TeamTimezoneEnum = "America/Campo_Grande"
	TeamTimezoneEnumAmericaCancun               TeamTimezoneEnum = "America/Cancun"
	TeamTimezoneEnumAmericaCaracas              TeamTimezoneEnum = "America/Caracas"
	TeamTimezoneEnumAmericaCayenne              TeamTimezoneEnum = "America/Cayenne"
	TeamTimezoneEnumAmericaCayman               TeamTimezoneEnum = "America/Cayman"
	TeamTimezoneEnumAmericaChicago              TeamTimezoneEnum = "America/Chicago"
	TeamTimezoneEnumAmericaChihuahua            TeamTimezoneEnum = "America/Chihuahua"
	TeamTimezoneEnumAmericaCostaRica            TeamTimezoneEnum = "America/Costa_Rica"
	TeamTimezoneEnumAmericaCreston              TeamTimezoneEnum = "America/Creston"
	TeamTimezoneEnumAmericaCuiaba               TeamTimezoneEnum = "America/Cuiaba"
	TeamTimezoneEnumAmericaCuracao              TeamTimezoneEnum = "America/Curacao"
	TeamTimezoneEnumAmericaDanmarkshavn         TeamTimezoneEnum = "America/Danmarkshavn"
	TeamTimezoneEnumAmericaDawson               TeamTimezoneEnum = "America/Dawson"
	TeamTimezoneEnumAmericaDawsonCreek          TeamTimezoneEnum = "America/Dawson_Creek"
	TeamTimezoneEnumAmericaDenver               TeamTimezoneEnum = "America/Denver"
	TeamTimezoneEnumAmericaDetroit              TeamTimezoneEnum = "America/Detroit"
	TeamTimezoneEnumAmericaDominica             TeamTimezoneEnum = "America/Dominica"
	TeamTimezoneEnumAmericaEdmonton             TeamTimezoneEnum = "America/Edmonton"
	TeamTimezoneEnumAmericaEirunepe             TeamTimezoneEnum = "America/Eirunepe"
	TeamTimezoneEnumAmericaElSalvador           TeamTimezoneEnum = "America/El_Salvador"
	TeamTimezoneEnumAmericaFortNelson           TeamTimezoneEnum = "America/Fort_Nelson"
	TeamTimezoneEnumAmericaFortaleza            TeamTimezoneEnum = "America/Fortaleza"
	TeamTimezoneEnumAmericaGlaceBay             TeamTimezoneEnum = "America/Glace_Bay"
	TeamTimezoneEnumAmericaGooseBay             TeamTimezoneEnum = "America/Goose_Bay"
	TeamTimezoneEnumAmericaGrandTurk            TeamTimezoneEnum = "America/Grand_Turk"
	TeamTimezoneEnumAmericaGrenada              TeamTimezoneEnum = "America/Grenada"
	TeamTimezoneEnumAmericaGuadeloupe           TeamTimezoneEnum = "America/Guadeloupe"
	TeamTimezoneEnumAmericaGuatemala            TeamTimezoneEnum = "America/Guatemala"
	TeamTimezoneEnumAmericaGuayaquil            TeamTimezoneEnum = "America/Guayaquil"
	TeamTimezoneEnumAmericaGuyana               TeamTimezoneEnum = "America/Guyana"
	TeamTimezoneEnumAmericaHalifax              TeamTimezoneEnum = "America/Halifax"
	TeamTimezoneEnumAmericaHavana               TeamTimezoneEnum = "America/Havana"
	TeamTimezoneEnumAmericaHermosillo           TeamTimezoneEnum = "America/Hermosillo"
	TeamTimezoneEnumAmericaIndianaIndianapolis  TeamTimezoneEnum = "America/Indiana/Indianapolis"
	TeamTimezoneEnumAmericaIndianaKnox          TeamTimezoneEnum = "America/Indiana/Knox"
	TeamTimezoneEnumAmericaIndianaMarengo       TeamTimezoneEnum = "America/Indiana/Marengo"
	TeamTimezoneEnumAmericaIndianaPetersburg    TeamTimezoneEnum = "America/Indiana/Petersburg"
	TeamTimezoneEnumAmericaIndianaTellCity      TeamTimezoneEnum = "America/Indiana/Tell_City"
	TeamTimezoneEnumAmericaIndianaVevay         TeamTimezoneEnum = "America/Indiana/Vevay"
	TeamTimezoneEnumAmericaIndianaVincennes     TeamTimezoneEnum = "America/Indiana/Vincennes"
	TeamTimezoneEnumAmericaIndianaWinamac       TeamTimezoneEnum = "America/Indiana/Winamac"
	TeamTimezoneEnumAmericaInuvik               TeamTimezoneEnum = "America/Inuvik"
	TeamTimezoneEnumAmericaIqaluit              TeamTimezoneEnum = "America/Iqaluit"
	TeamTimezoneEnumAmericaJamaica              TeamTimezoneEnum = "America/Jamaica"
	TeamTimezoneEnumAmericaJuneau               TeamTimezoneEnum = "America/Juneau"
	TeamTimezoneEnumAmericaKentuckyLouisville   TeamTimezoneEnum = "America/Kentucky/Louisville"
	TeamTimezoneEnumAmericaKentuckyMonticello   TeamTimezoneEnum = "America/Kentucky/Monticello"
	TeamTimezoneEnumAmericaKralendijk           TeamTimezoneEnum = "America/Kralendijk"
	TeamTimezoneEnumAmericaLaPaz                TeamTimezoneEnum = "America/La_Paz"
	TeamTimezoneEnumAmericaLima                 TeamTimezoneEnum = "America/Lima"
	TeamTimezoneEnumAmericaLosAngeles           TeamTimezoneEnum = "America/Los_Angeles"
	TeamTimezoneEnumAmericaLowerPrinces         TeamTimezoneEnum = "America/Lower_Princes"
	TeamTimezoneEnumAmericaMaceio               TeamTimezoneEnum = "America/Maceio"
	TeamTimezoneEnumAmericaManagua              TeamTimezoneEnum = "America/Managua"
	TeamTimezoneEnumAmericaManaus               TeamTimezoneEnum = "America/Manaus"
	TeamTimezoneEnumAmericaMarigot              TeamTimezoneEnum = "America/Marigot"
	TeamTimezoneEnumAmericaMartinique           TeamTimezoneEnum = "America/Martinique"
	TeamTimezoneEnumAmericaMatamoros            TeamTimezoneEnum = "America/Matamoros"
	TeamTimezoneEnumAmericaMazatlan             TeamTimezoneEnum = "America/Mazatlan"
	TeamTimezoneEnumAmericaMenominee            TeamTimezoneEnum = "America/Menominee"
	TeamTimezoneEnumAmericaMerida               TeamTimezoneEnum = "America/Merida"
	TeamTimezoneEnumAmericaMetlakatla           TeamTimezoneEnum = "America/Metlakatla"
	TeamTimezoneEnumAmericaMexicoCity           TeamTimezoneEnum = "America/Mexico_City"
	TeamTimezoneEnumAmericaMiquelon             TeamTimezoneEnum = "America/Miquelon"
	TeamTimezoneEnumAmericaMoncton              TeamTimezoneEnum = "America/Moncton"
	TeamTimezoneEnumAmericaMonterrey            TeamTimezoneEnum = "America/Monterrey"
	TeamTimezoneEnumAmericaMontevideo           TeamTimezoneEnum = "America/Montevideo"
	TeamTimezoneEnumAmericaMontserrat           TeamTimezoneEnum = "America/Montserrat"
	TeamTimezoneEnumAmericaNassau               TeamTimezoneEnum = "America/Nassau"
	TeamTimezoneEnumAmericaNewYork              TeamTimezoneEnum = "America/New_York"
	TeamTimezoneEnumAmericaNipigon              TeamTimezoneEnum = "America/Nipigon"
	TeamTimezoneEnumAmericaNome                 TeamTimezoneEnum = "America/Nome"
	TeamTimezoneEnumAmericaNoronha              TeamTimezoneEnum = "America/Noronha"
	TeamTimezoneEnumAmericaNorthDakotaBeulah    TeamTimezoneEnum = "America/North_Dakota/Beulah"
	TeamTimezoneEnumAmericaNorthDakotaCenter    TeamTimezoneEnum = "America/North_Dakota/Center"
	TeamTimezoneEnumAmericaNorthDakotaNewSalem  TeamTimezoneEnum = "America/North_Dakota/New_Salem"
	TeamTimezoneEnumAmericaNuuk                 TeamTimezoneEnum = "America/Nuuk"
	TeamTimezoneEnumAmericaOjinaga              TeamTimezoneEnum = "America/Ojinaga"
	TeamTimezoneEnumAmericaPanama               TeamTimezoneEnum = "America/Panama"
	TeamTimezoneEnumAmericaPangnirtung          TeamTimezoneEnum = "America/Pangnirtung"
	TeamTimezoneEnumAmericaParamaribo           TeamTimezoneEnum = "America/Paramaribo"
	TeamTimezoneEnumAmericaPhoenix              TeamTimezoneEnum = "America/Phoenix"
	TeamTimezoneEnumAmericaPortAuPrince         TeamTimezoneEnum = "America/Port-au-Prince"
	TeamTimezoneEnumAmericaPortOfSpain          TeamTimezoneEnum = "America/Port_of_Spain"
	TeamTimezoneEnumAmericaPortoVelho           TeamTimezoneEnum = "America/Porto_Velho"
	TeamTimezoneEnumAmericaPuertoRico           TeamTimezoneEnum = "America/Puerto_Rico"
	TeamTimezoneEnumAmericaPuntaArenas          TeamTimezoneEnum = "America/Punta_Arenas"
	TeamTimezoneEnumAmericaRainyRiver           TeamTimezoneEnum = "America/Rainy_River"
	TeamTimezoneEnumAmericaRankinInlet          TeamTimezoneEnum = "America/Rankin_Inlet"
	TeamTimezoneEnumAmericaRecife               TeamTimezoneEnum = "America/Recife"
	TeamTimezoneEnumAmericaRegina               TeamTimezoneEnum = "America/Regina"
	TeamTimezoneEnumAmericaResolute             TeamTimezoneEnum = "America/Resolute"
	TeamTimezoneEnumAmericaRioBranco            TeamTimezoneEnum = "America/Rio_Branco"
	TeamTimezoneEnumAmericaSantarem             TeamTimezoneEnum = "America/Santarem"
	TeamTimezoneEnumAmericaSantiago             TeamTimezoneEnum = "America/Santiago"
	TeamTimezoneEnumAmericaSantoDomingo         TeamTimezoneEnum = "America/Santo_Domingo"
	TeamTimezoneEnumAmericaSaoPaulo             TeamTimezoneEnum = "America/Sao_Paulo"
	TeamTimezoneEnumAmericaScoresbysund         TeamTimezoneEnum = "America/Scoresbysund"
	TeamTimezoneEnumAmericaSitka                TeamTimezoneEnum = "America/Sitka"
	TeamTimezoneEnumAmericaStBarthelemy         TeamTimezoneEnum = "America/St_Barthelemy"
	TeamTimezoneEnumAmericaStJohns              TeamTimezoneEnum = "America/St_Johns"
	TeamTimezoneEnumAmericaStKitts              TeamTimezoneEnum = "America/St_Kitts"
	TeamTimezoneEnumAmericaStLucia              TeamTimezoneEnum = "America/St_Lucia"
	TeamTimezoneEnumAmericaStThomas             TeamTimezoneEnum = "America/St_Thomas"
	TeamTimezoneEnumAmericaStVincent            TeamTimezoneEnum = "America/St_Vincent"
	TeamTimezoneEnumAmericaSwiftCurrent         TeamTimezoneEnum = "America/Swift_Current"
	TeamTimezoneEnumAmericaTegucigalpa          TeamTimezoneEnum = "America/Tegucigalpa"
	TeamTimezoneEnumAmericaThule                TeamTimezoneEnum = "America/Thule"
	TeamTimezoneEnumAmericaThunderBay           TeamTimezoneEnum = "America/Thunder_Bay"
	TeamTimezoneEnumAmericaTijuana              TeamTimezoneEnum = "America/Tijuana"
	TeamTimezoneEnumAmericaToronto              TeamTimezoneEnum = "America/Toronto"
	TeamTimezoneEnumAmericaTortola              TeamTimezoneEnum = "America/Tortola"
	TeamTimezoneEnumAmericaVancouver            TeamTimezoneEnum = "America/Vancouver"
	TeamTimezoneEnumAmericaWhitehorse           TeamTimezoneEnum = "America/Whitehorse"
	TeamTimezoneEnumAmericaWinnipeg             TeamTimezoneEnum = "America/Winnipeg"
	TeamTimezoneEnumAmericaYakutat              TeamTimezoneEnum = "America/Yakutat"
	TeamTimezoneEnumAmericaYellowknife          TeamTimezoneEnum = "America/Yellowknife"
	TeamTimezoneEnumAntarcticaCasey             TeamTimezoneEnum = "Antarctica/Casey"
	TeamTimezoneEnumAntarcticaDavis             TeamTimezoneEnum = "Antarctica/Davis"
	TeamTimezoneEnumAntarcticaDumontDUrville    TeamTimezoneEnum = "Antarctica/DumontDUrville"
	TeamTimezoneEnumAntarcticaMacquarie         TeamTimezoneEnum = "Antarctica/Macquarie"
	TeamTimezoneEnumAntarcticaMawson            TeamTimezoneEnum = "Antarctica/Mawson"
	TeamTimezoneEnumAntarcticaMcMurdo           TeamTimezoneEnum = "Antarctica/McMurdo"
	TeamTimezoneEnumAntarcticaPalmer            TeamTimezoneEnum = "Antarctica/Palmer"
	TeamTimezoneEnumAntarcticaRothera           TeamTimezoneEnum = "Antarctica/Rothera"
	TeamTimezoneEnumAntarcticaSyowa             TeamTimezoneEnum = "Antarctica/Syowa"
	TeamTimezoneEnumAntarcticaTroll             TeamTimezoneEnum = "Antarctica/Troll"
	TeamTimezoneEnumAntarcticaVostok            TeamTimezoneEnum = "Antarctica/Vostok"
	TeamTimezoneEnumArcticLongyearbyen          TeamTimezoneEnum = "Arctic/Longyearbyen"
	TeamTimezoneEnumAsiaAden                    TeamTimezoneEnum = "Asia/Aden"
	TeamTimezoneEnumAsiaAlmaty                  TeamTimezoneEnum = "Asia/Almaty"
	TeamTimezoneEnumAsiaAmman                   TeamTimezoneEnum = "Asia/Amman"
	TeamTimezoneEnumAsiaAnadyr                  TeamTimezoneEnum = "Asia/Anadyr"
	TeamTimezoneEnumAsiaAqtau                   TeamTimezoneEnum = "Asia/Aqtau"
	TeamTimezoneEnumAsiaAqtobe                  TeamTimezoneEnum = "Asia/Aqtobe"
	TeamTimezoneEnumAsiaAshgabat                TeamTimezoneEnum = "Asia/Ashgabat"
	TeamTimezoneEnumAsiaAtyrau                  TeamTimezoneEnum = "Asia/Atyrau"
	TeamTimezoneEnumAsiaBaghdad                 TeamTimezoneEnum = "Asia/Baghdad"
	TeamTimezoneEnumAsiaBahrain                 TeamTimezoneEnum = "Asia/Bahrain"
	TeamTimezoneEnumAsiaBaku                    TeamTimezoneEnum = "Asia/Baku"
	TeamTimezoneEnumAsiaBangkok                 TeamTimezoneEnum = "Asia/Bangkok"
	TeamTimezoneEnumAsiaBarnaul                 TeamTimezoneEnum = "Asia/Barnaul"
	TeamTimezoneEnumAsiaBeirut                  TeamTimezoneEnum = "Asia/Beirut"
	TeamTimezoneEnumAsiaBishkek                 TeamTimezoneEnum = "Asia/Bishkek"
	TeamTimezoneEnumAsiaBrunei                  TeamTimezoneEnum = "Asia/Brunei"
	TeamTimezoneEnumAsiaChita                   TeamTimezoneEnum = "Asia/Chita"
	TeamTimezoneEnumAsiaChoibalsan              TeamTimezoneEnum = "Asia/Choibalsan"
	TeamTimezoneEnumAsiaColombo                 TeamTimezoneEnum = "Asia/Colombo"
	TeamTimezoneEnumAsiaDamascus                TeamTimezoneEnum = "Asia/Damascus"
	TeamTimezoneEnumAsiaDhaka                   TeamTimezoneEnum = "Asia/Dhaka"
	TeamTimezoneEnumAsiaDili                    TeamTimezoneEnum = "Asia/Dili"
	TeamTimezoneEnumAsiaDubai                   TeamTimezoneEnum = "Asia/Dubai"
	TeamTimezoneEnumAsiaDushanbe                TeamTimezoneEnum = "Asia/Dushanbe"
	TeamTimezoneEnumAsiaFamagusta               TeamTimezoneEnum = "Asia/Famagusta"
	TeamTimezoneEnumAsiaGaza                    TeamTimezoneEnum = "Asia/Gaza"
	TeamTimezoneEnumAsiaHebron                  TeamTimezoneEnum = "Asia/Hebron"
	TeamTimezoneEnumAsiaHoChiMinh               TeamTimezoneEnum = "Asia/Ho_Chi_Minh"
	TeamTimezoneEnumAsiaHongKong                TeamTimezoneEnum = "Asia/Hong_Kong"
	TeamTimezoneEnumAsiaHovd                    TeamTimezoneEnum = "Asia/Hovd"
	TeamTimezoneEnumAsiaIrkutsk                 TeamTimezoneEnum = "Asia/Irkutsk"
	TeamTimezoneEnumAsiaJakarta                 TeamTimezoneEnum = "Asia/Jakarta"
	TeamTimezoneEnumAsiaJayapura                TeamTimezoneEnum = "Asia/Jayapura"
	TeamTimezoneEnumAsiaJerusalem               TeamTimezoneEnum = "Asia/Jerusalem"
	TeamTimezoneEnumAsiaKabul                   TeamTimezoneEnum = "Asia/Kabul"
	TeamTimezoneEnumAsiaKamchatka               TeamTimezoneEnum = "Asia/Kamchatka"
	TeamTimezoneEnumAsiaKarachi                 TeamTimezoneEnum = "Asia/Karachi"
	TeamTimezoneEnumAsiaKathmandu               TeamTimezoneEnum = "Asia/Kathmandu"
	TeamTimezoneEnumAsiaKhandyga                TeamTimezoneEnum = "Asia/Khandyga"
	TeamTimezoneEnumAsiaKolkata                 TeamTimezoneEnum = "Asia/Kolkata"
	TeamTimezoneEnumAsiaKrasnoyarsk             TeamTimezoneEnum = "Asia/Krasnoyarsk"
	TeamTimezoneEnumAsiaKualaLumpur             TeamTimezoneEnum = "Asia/Kuala_Lumpur"
	TeamTimezoneEnumAsiaKuching                 TeamTimezoneEnum = "Asia/Kuching"
	TeamTimezoneEnumAsiaKuwait                  TeamTimezoneEnum = "Asia/Kuwait"
	TeamTimezoneEnumAsiaMacau                   TeamTimezoneEnum = "Asia/Macau"
	TeamTimezoneEnumAsiaMagadan                 TeamTimezoneEnum = "Asia/Magadan"
	TeamTimezoneEnumAsiaMakassar                TeamTimezoneEnum = "Asia/Makassar"
	TeamTimezoneEnumAsiaManila                  TeamTimezoneEnum = "Asia/Manila"
	TeamTimezoneEnumAsiaMuscat                  TeamTimezoneEnum = "Asia/Muscat"
	TeamTimezoneEnumAsiaNicosia                 TeamTimezoneEnum = "Asia/Nicosia"
	TeamTimezoneEnumAsiaNovokuznetsk            TeamTimezoneEnum = "Asia/Novokuznetsk"
	TeamTimezoneEnumAsiaNovosibirsk             TeamTimezoneEnum = "Asia/Novosibirsk"
	TeamTimezoneEnumAsiaOmsk                    TeamTimezoneEnum = "Asia/Omsk"
	TeamTimezoneEnumAsiaOral                    TeamTimezoneEnum = "Asia/Oral"
	TeamTimezoneEnumAsiaPhnomPenh               TeamTimezoneEnum = "Asia/Phnom_Penh"
	TeamTimezoneEnumAsiaPontianak               TeamTimezoneEnum = "Asia/Pontianak"
	TeamTimezoneEnumAsiaPyongyang               TeamTimezoneEnum = "Asia/Pyongyang"
	TeamTimezoneEnumAsiaQatar                   TeamTimezoneEnum = "Asia/Qatar"
	TeamTimezoneEnumAsiaQostanay                TeamTimezoneEnum = "Asia/Qostanay"
	TeamTimezoneEnumAsiaQyzylorda               TeamTimezoneEnum = "Asia/Qyzylorda"
	TeamTimezoneEnumAsiaRiyadh                  TeamTimezoneEnum = "Asia/Riyadh"
	TeamTimezoneEnumAsiaSakhalin                TeamTimezoneEnum = "Asia/Sakhalin"
	TeamTimezoneEnumAsiaSamarkand               TeamTimezoneEnum = "Asia/Samarkand"
	TeamTimezoneEnumAsiaSeoul                   TeamTimezoneEnum = "Asia/Seoul"
	TeamTimezoneEnumAsiaShanghai                TeamTimezoneEnum = "Asia/Shanghai"
	TeamTimezoneEnumAsiaSingapore               TeamTimezoneEnum = "Asia/Singapore"
	TeamTimezoneEnumAsiaSrednekolymsk           TeamTimezoneEnum = "Asia/Srednekolymsk"
	TeamTimezoneEnumAsiaTaipei                  TeamTimezoneEnum = "Asia/Taipei"
	TeamTimezoneEnumAsiaTashkent                TeamTimezoneEnum = "Asia/Tashkent"
	TeamTimezoneEnumAsiaTbilisi                 TeamTimezoneEnum = "Asia/Tbilisi"
	TeamTimezoneEnumAsiaTehran                  TeamTimezoneEnum = "Asia/Tehran"
	TeamTimezoneEnumAsiaThimphu                 TeamTimezoneEnum = "Asia/Thimphu"
	TeamTimezoneEnumAsiaTokyo                   TeamTimezoneEnum = "Asia/Tokyo"
	TeamTimezoneEnumAsiaTomsk                   TeamTimezoneEnum = "Asia/Tomsk"
	TeamTimezoneEnumAsiaUlaanbaatar             TeamTimezoneEnum = "Asia/Ulaanbaatar"
	TeamTimezoneEnumAsiaUrumqi                  TeamTimezoneEnum = "Asia/Urumqi"
	TeamTimezoneEnumAsiaUstNera                 TeamTimezoneEnum = "Asia/Ust-Nera"
	TeamTimezoneEnumAsiaVientiane               TeamTimezoneEnum = "Asia/Vientiane"
	TeamTimezoneEnumAsiaVladivostok             TeamTimezoneEnum = "Asia/Vladivostok"
	TeamTimezoneEnumAsiaYakutsk                 TeamTimezoneEnum = "Asia/Yakutsk"
	TeamTimezoneEnumAsiaYangon                  TeamTimezoneEnum = "Asia/Yangon"
	TeamTimezoneEnumAsiaYekaterinburg           TeamTimezoneEnum = "Asia/Yekaterinburg"
	TeamTimezoneEnumAsiaYerevan                 TeamTimezoneEnum = "Asia/Yerevan"
	TeamTimezoneEnumAtlanticAzores              TeamTimezoneEnum = "Atlantic/Azores"
	TeamTimezoneEnumAtlanticBermuda             TeamTimezoneEnum = "Atlantic/Bermuda"
	TeamTimezoneEnumAtlanticCanary              TeamTimezoneEnum = "Atlantic/Canary"
	TeamTimezoneEnumAtlanticCapeVerde           TeamTimezoneEnum = "Atlantic/Cape_Verde"
	TeamTimezoneEnumAtlanticFaroe               TeamTimezoneEnum = "Atlantic/Faroe"
	TeamTimezoneEnumAtlanticMadeira             TeamTimezoneEnum = "Atlantic/Madeira"
	TeamTimezoneEnumAtlanticReykjavik           TeamTimezoneEnum = "Atlantic/Reykjavik"
	TeamTimezoneEnumAtlanticSouthGeorgia        TeamTimezoneEnum = "Atlantic/South_Georgia"
	TeamTimezoneEnumAtlanticStHelena            TeamTimezoneEnum = "Atlantic/St_Helena"
	TeamTimezoneEnumAtlanticStanley             TeamTimezoneEnum = "Atlantic/Stanley"
	TeamTimezoneEnumAustraliaAdelaide           TeamTimezoneEnum = "Australia/Adelaide"
	TeamTimezoneEnumAustraliaBrisbane           TeamTimezoneEnum = "Australia/Brisbane"
	TeamTimezoneEnumAustraliaBrokenHill         TeamTimezoneEnum = "Australia/Broken_Hill"
	TeamTimezoneEnumAustraliaDarwin             TeamTimezoneEnum = "Australia/Darwin"
	TeamTimezoneEnumAustraliaEucla              TeamTimezoneEnum = "Australia/Eucla"
	TeamTimezoneEnumAustraliaHobart             TeamTimezoneEnum = "Australia/Hobart"
	TeamTimezoneEnumAustraliaLindeman           TeamTimezoneEnum = "Australia/Lindeman"
	TeamTimezoneEnumAustraliaLordHowe           TeamTimezoneEnum = "Australia/Lord_Howe"
	TeamTimezoneEnumAustraliaMelbourne          TeamTimezoneEnum = "Australia/Melbourne"
	TeamTimezoneEnumAustraliaPerth              TeamTimezoneEnum = "Australia/Perth"
	TeamTimezoneEnumAustraliaSydney             TeamTimezoneEnum = "Australia/Sydney"
	TeamTimezoneEnumCanadaAtlantic              TeamTimezoneEnum = "Canada/Atlantic"
	TeamTimezoneEnumCanadaCentral               TeamTimezoneEnum = "Canada/Central"
	TeamTimezoneEnumCanadaEastern               TeamTimezoneEnum = "Canada/Eastern"
	TeamTimezoneEnumCanadaMountain              TeamTimezoneEnum = "Canada/Mountain"
	TeamTimezoneEnumCanadaNewfoundland          TeamTimezoneEnum = "Canada/Newfoundland"
	TeamTimezoneEnumCanadaPacific               TeamTimezoneEnum = "Canada/Pacific"
	TeamTimezoneEnumEuropeAmsterdam             TeamTimezoneEnum = "Europe/Amsterdam"
	TeamTimezoneEnumEuropeAndorra               TeamTimezoneEnum = "Europe/Andorra"
	TeamTimezoneEnumEuropeAstrakhan             TeamTimezoneEnum = "Europe/Astrakhan"
	TeamTimezoneEnumEuropeAthens                TeamTimezoneEnum = "Europe/Athens"
	TeamTimezoneEnumEuropeBelgrade              TeamTimezoneEnum = "Europe/Belgrade"
	TeamTimezoneEnumEuropeBerlin                TeamTimezoneEnum = "Europe/Berlin"
	TeamTimezoneEnumEuropeBratislava            TeamTimezoneEnum = "Europe/Bratislava"
	TeamTimezoneEnumEuropeBrussels              TeamTimezoneEnum = "Europe/Brussels"
	TeamTimezoneEnumEuropeBucharest             TeamTimezoneEnum = "Europe/Bucharest"
	TeamTimezoneEnumEuropeBudapest              TeamTimezoneEnum = "Europe/Budapest"
	TeamTimezoneEnumEuropeBusingen              TeamTimezoneEnum = "Europe/Busingen"
	TeamTimezoneEnumEuropeChisinau              TeamTimezoneEnum = "Europe/Chisinau"
	TeamTimezoneEnumEuropeCopenhagen            TeamTimezoneEnum = "Europe/Copenhagen"
	TeamTimezoneEnumEuropeDublin                TeamTimezoneEnum = "Europe/Dublin"
	TeamTimezoneEnumEuropeGibraltar             TeamTimezoneEnum = "Europe/Gibraltar"
	TeamTimezoneEnumEuropeGuernsey              TeamTimezoneEnum = "Europe/Guernsey"
	TeamTimezoneEnumEuropeHelsinki              TeamTimezoneEnum = "Europe/Helsinki"
	TeamTimezoneEnumEuropeIsleOfMan             TeamTimezoneEnum = "Europe/Isle_of_Man"
	TeamTimezoneEnumEuropeIstanbul              TeamTimezoneEnum = "Europe/Istanbul"
	TeamTimezoneEnumEuropeJersey                TeamTimezoneEnum = "Europe/Jersey"
	TeamTimezoneEnumEuropeKaliningrad           TeamTimezoneEnum = "Europe/Kaliningrad"
	TeamTimezoneEnumEuropeKiev                  TeamTimezoneEnum = "Europe/Kiev"
	TeamTimezoneEnumEuropeKirov                 TeamTimezoneEnum = "Europe/Kirov"
	TeamTimezoneEnumEuropeLisbon                TeamTimezoneEnum = "Europe/Lisbon"
	TeamTimezoneEnumEuropeLjubljana             TeamTimezoneEnum = "Europe/Ljubljana"
	TeamTimezoneEnumEuropeLondon                TeamTimezoneEnum = "Europe/London"
	TeamTimezoneEnumEuropeLuxembourg            TeamTimezoneEnum = "Europe/Luxembourg"
	TeamTimezoneEnumEuropeMadrid                TeamTimezoneEnum = "Europe/Madrid"
	TeamTimezoneEnumEuropeMalta                 TeamTimezoneEnum = "Europe/Malta"
	TeamTimezoneEnumEuropeMariehamn             TeamTimezoneEnum = "Europe/Mariehamn"
	TeamTimezoneEnumEuropeMinsk                 TeamTimezoneEnum = "Europe/Minsk"
	TeamTimezoneEnumEuropeMonaco                TeamTimezoneEnum = "Europe/Monaco"
	TeamTimezoneEnumEuropeMoscow                TeamTimezoneEnum = "Europe/Moscow"
	TeamTimezoneEnumEuropeOslo                  TeamTimezoneEnum = "Europe/Oslo"
	TeamTimezoneEnumEuropeParis                 TeamTimezoneEnum = "Europe/Paris"
	TeamTimezoneEnumEuropePodgorica             TeamTimezoneEnum = "Europe/Podgorica"
	TeamTimezoneEnumEuropePrague                TeamTimezoneEnum = "Europe/Prague"
	TeamTimezoneEnumEuropeRiga                  TeamTimezoneEnum = "Europe/Riga"
	TeamTimezoneEnumEuropeRome                  TeamTimezoneEnum = "Europe/Rome"
	TeamTimezoneEnumEuropeSamara                TeamTimezoneEnum = "Europe/Samara"
	TeamTimezoneEnumEuropeSanMarino             TeamTimezoneEnum = "Europe/San_Marino"
	TeamTimezoneEnumEuropeSarajevo              TeamTimezoneEnum = "Europe/Sarajevo"
	TeamTimezoneEnumEuropeSaratov               TeamTimezoneEnum = "Europe/Saratov"
	TeamTimezoneEnumEuropeSimferopol            TeamTimezoneEnum = "Europe/Simferopol"
	TeamTimezoneEnumEuropeSkopje                TeamTimezoneEnum = "Europe/Skopje"
	TeamTimezoneEnumEuropeSofia                 TeamTimezoneEnum = "Europe/Sofia"
	TeamTimezoneEnumEuropeStockholm             TeamTimezoneEnum = "Europe/Stockholm"
	TeamTimezoneEnumEuropeTallinn               TeamTimezoneEnum = "Europe/Tallinn"
	TeamTimezoneEnumEuropeTirane                TeamTimezoneEnum = "Europe/Tirane"
	TeamTimezoneEnumEuropeUlyanovsk             TeamTimezoneEnum = "Europe/Ulyanovsk"
	TeamTimezoneEnumEuropeUzhgorod              TeamTimezoneEnum = "Europe/Uzhgorod"
	TeamTimezoneEnumEuropeVaduz                 TeamTimezoneEnum = "Europe/Vaduz"
	TeamTimezoneEnumEuropeVatican               TeamTimezoneEnum = "Europe/Vatican"
	TeamTimezoneEnumEuropeVienna                TeamTimezoneEnum = "Europe/Vienna"
	TeamTimezoneEnumEuropeVilnius               TeamTimezoneEnum = "Europe/Vilnius"
	TeamTimezoneEnumEuropeVolgograd             TeamTimezoneEnum = "Europe/Volgograd"
	TeamTimezoneEnumEuropeWarsaw                TeamTimezoneEnum = "Europe/Warsaw"
	TeamTimezoneEnumEuropeZagreb                TeamTimezoneEnum = "Europe/Zagreb"
	TeamTimezoneEnumEuropeZaporozhye            TeamTimezoneEnum = "Europe/Zaporozhye"
	TeamTimezoneEnumEuropeZurich                TeamTimezoneEnum = "Europe/Zurich"
	TeamTimezoneEnumGmt                         TeamTimezoneEnum = "GMT"
	TeamTimezoneEnumIndianAntananarivo          TeamTimezoneEnum = "Indian/Antananarivo"
	TeamTimezoneEnumIndianChagos                TeamTimezoneEnum = "Indian/Chagos"
	TeamTimezoneEnumIndianChristmas             TeamTimezoneEnum = "Indian/Christmas"
	TeamTimezoneEnumIndianCocos                 TeamTimezoneEnum = "Indian/Cocos"
	TeamTimezoneEnumIndianComoro                TeamTimezoneEnum = "Indian/Comoro"
	TeamTimezoneEnumIndianKerguelen             TeamTimezoneEnum = "Indian/Kerguelen"
	TeamTimezoneEnumIndianMahe                  TeamTimezoneEnum = "Indian/Mahe"
	TeamTimezoneEnumIndianMaldives              TeamTimezoneEnum = "Indian/Maldives"
	TeamTimezoneEnumIndianMauritius             TeamTimezoneEnum = "Indian/Mauritius"
	TeamTimezoneEnumIndianMayotte               TeamTimezoneEnum = "Indian/Mayotte"
	TeamTimezoneEnumIndianReunion               TeamTimezoneEnum = "Indian/Reunion"
	TeamTimezoneEnumPacificApia                 TeamTimezoneEnum = "Pacific/Apia"
	TeamTimezoneEnumPacificAuckland             TeamTimezoneEnum = "Pacific/Auckland"
	TeamTimezoneEnumPacificBougainville         TeamTimezoneEnum = "Pacific/Bougainville"
	TeamTimezoneEnumPacificChatham              TeamTimezoneEnum = "Pacific/Chatham"
	TeamTimezoneEnumPacificChuuk                TeamTimezoneEnum = "Pacific/Chuuk"
	TeamTimezoneEnumPacificEaster               TeamTimezoneEnum = "Pacific/Easter"
	TeamTimezoneEnumPacificEfate                TeamTimezoneEnum = "Pacific/Efate"
	TeamTimezoneEnumPacificEnderbury            TeamTimezoneEnum = "Pacific/Enderbury"
	TeamTimezoneEnumPacificFakaofo              TeamTimezoneEnum = "Pacific/Fakaofo"
	TeamTimezoneEnumPacificFiji                 TeamTimezoneEnum = "Pacific/Fiji"
	TeamTimezoneEnumPacificFunafuti             TeamTimezoneEnum = "Pacific/Funafuti"
	TeamTimezoneEnumPacificGalapagos            TeamTimezoneEnum = "Pacific/Galapagos"
	TeamTimezoneEnumPacificGambier              TeamTimezoneEnum = "Pacific/Gambier"
	TeamTimezoneEnumPacificGuadalcanal          TeamTimezoneEnum = "Pacific/Guadalcanal"
	TeamTimezoneEnumPacificGuam                 TeamTimezoneEnum = "Pacific/Guam"
	TeamTimezoneEnumPacificHonolulu             TeamTimezoneEnum = "Pacific/Honolulu"
	TeamTimezoneEnumPacificKiritimati           TeamTimezoneEnum = "Pacific/Kiritimati"
	TeamTimezoneEnumPacificKosrae               TeamTimezoneEnum = "Pacific/Kosrae"
	TeamTimezoneEnumPacificKwajalein            TeamTimezoneEnum = "Pacific/Kwajalein"
	TeamTimezoneEnumPacificMajuro               TeamTimezoneEnum = "Pacific/Majuro"
	TeamTimezoneEnumPacificMarquesas            TeamTimezoneEnum = "Pacific/Marquesas"
	TeamTimezoneEnumPacificMidway               TeamTimezoneEnum = "Pacific/Midway"
	TeamTimezoneEnumPacificNauru                TeamTimezoneEnum = "Pacific/Nauru"
	TeamTimezoneEnumPacificNiue                 TeamTimezoneEnum = "Pacific/Niue"
	TeamTimezoneEnumPacificNorfolk              TeamTimezoneEnum = "Pacific/Norfolk"
	TeamTimezoneEnumPacificNoumea               TeamTimezoneEnum = "Pacific/Noumea"
	TeamTimezoneEnumPacificPagoPago             TeamTimezoneEnum = "Pacific/Pago_Pago"
	TeamTimezoneEnumPacificPalau                TeamTimezoneEnum = "Pacific/Palau"
	TeamTimezoneEnumPacificPitcairn             TeamTimezoneEnum = "Pacific/Pitcairn"
	TeamTimezoneEnumPacificPohnpei              TeamTimezoneEnum = "Pacific/Pohnpei"
	TeamTimezoneEnumPacificPortMoresby          TeamTimezoneEnum = "Pacific/Port_Moresby"
	TeamTimezoneEnumPacificRarotonga            TeamTimezoneEnum = "Pacific/Rarotonga"
	TeamTimezoneEnumPacificSaipan               TeamTimezoneEnum = "Pacific/Saipan"
	TeamTimezoneEnumPacificTahiti               TeamTimezoneEnum = "Pacific/Tahiti"
	TeamTimezoneEnumPacificTarawa               TeamTimezoneEnum = "Pacific/Tarawa"
	TeamTimezoneEnumPacificTongatapu            TeamTimezoneEnum = "Pacific/Tongatapu"
	TeamTimezoneEnumPacificWake                 TeamTimezoneEnum = "Pacific/Wake"
	TeamTimezoneEnumPacificWallis               TeamTimezoneEnum = "Pacific/Wallis"
	TeamTimezoneEnumUsAlaska                    TeamTimezoneEnum = "US/Alaska"
	TeamTimezoneEnumUsArizona                   TeamTimezoneEnum = "US/Arizona"
	TeamTimezoneEnumUsCentral                   TeamTimezoneEnum = "US/Central"
	TeamTimezoneEnumUsEastern                   TeamTimezoneEnum = "US/Eastern"
	TeamTimezoneEnumUsHawaii                    TeamTimezoneEnum = "US/Hawaii"
	TeamTimezoneEnumUsMountain                  TeamTimezoneEnum = "US/Mountain"
	TeamTimezoneEnumUsPacific                   TeamTimezoneEnum = "US/Pacific"
	TeamTimezoneEnumUtc                         TeamTimezoneEnum = "UTC"
)

type Team struct {
	AccessControl                    *bool                  `json:"access_control,omitempty"`
	AnonymizeIps                     *bool                  `json:"anonymize_ips,omitempty"`
	APIToken                         string                 `json:"api_token"`
	AppUrls                          []string               `json:"app_urls,omitempty"`
	CaptureConsoleLogOptIn           *bool                  `json:"capture_console_log_opt_in,omitempty"`
	CapturePerformanceOptIn          *bool                  `json:"capture_performance_opt_in,omitempty"`
	CompletedSnippetOnboarding       *bool                  `json:"completed_snippet_onboarding,omitempty"`
	CorrelationConfig                map[string]interface{} `json:"correlation_config,omitempty"`
	CreatedAt                        time.Time              `json:"created_at"`
	DataAttributes                   map[string]interface{} `json:"data_attributes,omitempty"`
	EffectiveMembershipLevel         int64                  `json:"effective_membership_level"`
	GroupsOnEventsQueryingEnabled    bool                   `json:"groups_on_events_querying_enabled"`
	HasGroupTypes                    bool                   `json:"has_group_types"`
	ID                               int64                  `json:"id"`
	IngestedEvent                    bool                   `json:"ingested_event"`
	InjectWebApps                    *bool                  `json:"inject_web_apps,omitempty"`
	IsDemo                           *bool                  `json:"is_demo,omitempty"`
	LiveEventsColumns                []string               `json:"live_events_columns,omitempty"`
	Name                             *string                `json:"name,omitempty"`
	Organization                     string                 `json:"organization"`
	PathCleaningFilters              map[string]interface{} `json:"path_cleaning_filters,omitempty"`
	PersonDisplayNameProperties      []string               `json:"person_display_name_properties,omitempty"`
	PersonOnEventsQueryingEnabled    bool                   `json:"person_on_events_querying_enabled"`
	PrimaryDashboard                 *int64                 `json:"primary_dashboard,omitempty"`
	RecordingDomains                 []string               `json:"recording_domains,omitempty"`
	SessionRecordingOptIn            *bool                  `json:"session_recording_opt_in,omitempty"`
	SlackIncomingWebhook             *string                `json:"slack_incoming_webhook,omitempty"`
	TestAccountFilters               map[string]interface{} `json:"test_account_filters,omitempty"`
	TestAccountFiltersDefaultChecked *bool                  `json:"test_account_filters_default_checked,omitempty"`
	Timezone                         *TeamTimezoneEnum      `json:"timezone,omitempty"`
	UpdatedAt                        time.Time              `json:"updated_at"`
	UUID                             string                 `json:"uuid"`
}

type TeamInput struct {
	AccessControl                    *bool                  `json:"access_control,omitempty" form:"name=access_control" multipartForm:"name=access_control"`
	AnonymizeIps                     *bool                  `json:"anonymize_ips,omitempty" form:"name=anonymize_ips" multipartForm:"name=anonymize_ips"`
	AppUrls                          []string               `json:"app_urls,omitempty" form:"name=app_urls" multipartForm:"name=app_urls"`
	CaptureConsoleLogOptIn           *bool                  `json:"capture_console_log_opt_in,omitempty" form:"name=capture_console_log_opt_in" multipartForm:"name=capture_console_log_opt_in"`
	CapturePerformanceOptIn          *bool                  `json:"capture_performance_opt_in,omitempty" form:"name=capture_performance_opt_in" multipartForm:"name=capture_performance_opt_in"`
	CompletedSnippetOnboarding       *bool                  `json:"completed_snippet_onboarding,omitempty" form:"name=completed_snippet_onboarding" multipartForm:"name=completed_snippet_onboarding"`
	CorrelationConfig                map[string]interface{} `json:"correlation_config,omitempty" form:"name=correlation_config,json" multipartForm:"name=correlation_config,json"`
	DataAttributes                   map[string]interface{} `json:"data_attributes,omitempty" form:"name=data_attributes,json" multipartForm:"name=data_attributes,json"`
	InjectWebApps                    *bool                  `json:"inject_web_apps,omitempty" form:"name=inject_web_apps" multipartForm:"name=inject_web_apps"`
	IsDemo                           *bool                  `json:"is_demo,omitempty" form:"name=is_demo" multipartForm:"name=is_demo"`
	LiveEventsColumns                []string               `json:"live_events_columns,omitempty" form:"name=live_events_columns" multipartForm:"name=live_events_columns"`
	Name                             *string                `json:"name,omitempty" form:"name=name" multipartForm:"name=name"`
	PathCleaningFilters              map[string]interface{} `json:"path_cleaning_filters,omitempty" form:"name=path_cleaning_filters,json" multipartForm:"name=path_cleaning_filters,json"`
	PersonDisplayNameProperties      []string               `json:"person_display_name_properties,omitempty" form:"name=person_display_name_properties" multipartForm:"name=person_display_name_properties"`
	PrimaryDashboard                 *int64                 `json:"primary_dashboard,omitempty" form:"name=primary_dashboard" multipartForm:"name=primary_dashboard"`
	RecordingDomains                 []string               `json:"recording_domains,omitempty" form:"name=recording_domains" multipartForm:"name=recording_domains"`
	SessionRecordingOptIn            *bool                  `json:"session_recording_opt_in,omitempty" form:"name=session_recording_opt_in" multipartForm:"name=session_recording_opt_in"`
	SlackIncomingWebhook             *string                `json:"slack_incoming_webhook,omitempty" form:"name=slack_incoming_webhook" multipartForm:"name=slack_incoming_webhook"`
	TestAccountFilters               map[string]interface{} `json:"test_account_filters,omitempty" form:"name=test_account_filters,json" multipartForm:"name=test_account_filters,json"`
	TestAccountFiltersDefaultChecked *bool                  `json:"test_account_filters_default_checked,omitempty" form:"name=test_account_filters_default_checked" multipartForm:"name=test_account_filters_default_checked"`
	Timezone                         *TeamTimezoneEnum      `json:"timezone,omitempty" form:"name=timezone" multipartForm:"name=timezone"`
}
